#!/bin/sh

export CC=afl-gcc
export CXX=afl-g++

# NOTE: we're skipping tests to speed things up.
export DEB_BUILD_OPTIONS=nocheck

# Use ASAN - Address SANitizer. This will crash on subtle memory errors.
AFL_USE_ASAN=1

# No idea if it's actually necessary if we have ASAN - if you have an opinion,
# let me know.
export AFL_HARDEN=1

export FORCE_UNSAFE_CONFIGURE=1  # for coreutils root build check.
export ASAN_OPTIONS=detect_leaks=0  # we don't need leak checks while building

# In case of e.g. gimp, dpkg-gensymbols complains after having detected new
# symbols introduced by AFL. Let's disable the check.
export DPKG_GENSYMBOLS_CHECK_LEVEL=0

# We overwrote /usr/bin/gcc, so we need to specify AFL_CC to avoid afl-gcc
# calling itself.
#
# NOTE: This is generated in Dockerfile.
