#!/bin/bash

# Prepares a directory with Debian packages compiled in a form ready for
# fuzzing with american fuzzy lop. See README.md for more details.
#
# AUTHOR: Jacek "d33tah" Wielemborek, licensed under WTFPL.

. /etc/profile.d/afl-sh-profile

if [ "$#" = "0" ]; then

        if [ ! -f ~/packages.list ]; then
            # We skip the first 6 lines because of a quite lengthy header.
            dpkg -l | tail -n +6 | awk '{ print $2 }' > ~/packages.list
        fi

        PKGS=`cat ~/packages.list`
else
        PKGS=$@
fi

for pkg in $PKGS; do

        rm -rf ~/pkg/.* ~/pkg/*

        # Building some source packages results in more than one .deb file.
        # There's no point building coreutils multiple times just because we
        # need mount, libmount1 and libmount1-dev, for example.
        if [ -f ~/pkgs/${pkg}_* ]; then
            echo "Skipping $pkg because it's already in ~/pkgs."
            continue
        fi

        echo "Aflizing $pkg"

        cd ~/pkg
        apt-get build-dep -y $pkg 2>&1
        apt-get source $pkg 2>&1
        cd *

        ( dpkg-buildpackage -uc -us -Jauto 2>&1 | \
            tee ~/logs/${pkg}.txt ) || echo $pkg >> ~/failed

        mv ~/pkg/*.deb ~/pkgs

done | perl -pe '$|=1; print scalar(localtime()), ": ";'
