#!/bin/bash

# Make sure afl-gcc will be run. This forces us to set AFL_CC and AFL_CXX or
# otherwise afl-gcc will be trying to call itself by calling gcc.

echo "AFL_CC=`readlink $( readlink /etc/alternatives/cc) `" >> /etc/profile.d/afl-sh-profile
echo "AFL_CXX=`readlink $( readlink /etc/alternatives/c++) `" >> /etc/profile.d/afl-sh-profile

rm /usr/bin/cc && cp /usr/bin/afl-gcc /usr/bin/cc
rm /usr/bin/gcc && cp /usr/bin/afl-gcc /usr/bin/gcc
rm /usr/bin/g++ && cp /usr/bin/afl-g++ /usr/bin/g++
rm /usr/bin/x86_64-linux-gnu-gcc && cp /usr/bin/afl-gcc /usr/bin/x86_64-linux-gnu-gcc
rm /usr/bin/x86_64-linux-gnu-g++ && cp /usr/bin/afl-g++ /usr/bin/x86_64-linux-gnu-g++
